Silence errors about ambiguous NULL
These test queries produced error:

ERROR:  could not determine polymorphic type because input has type "unknown"

Because it's ambiguous what datatype the NULL is.